### PR TITLE
Upgraded to Font-Awesome 4.6.3

### PR DESCRIPTION
**Pull request by rvargas**

### CODE REVIEW

**Comment by rvargas** [comment]
@donbeave Hi! This is my first contribution to a plugin. Do these changes are automatically published? Thanks!

**Comment by donbeave** [comment]
Actually not, need to deploy. If you want you can fork this plugin and ask on Grails.org for access to become a main developer.

**Comment by rvargas** [comment]
I think I already have an access to grails.org, let me find it :)

**Comment by rvargas** [comment]
Done, I recovered my account. what's the next step?

**Comment by donbeave** [comment]
http://grails.org/plugins/submitPlugin
You can submit this plugin and tell them original author already gave you authority to publish plugin and link to this issue.

**Pull request merged**
