### PR TITLE
Upgraded to grails 3

### PR DESCRIPTION
**Pull request by PaulWaldo**
Hi Alexey,
This is my first stab at updating a plugin to grails 3 and I'd appreciate your feedback.  Thanks!

### CODE REVIEW

**Comment by donbeave** [comment]
Hi, Paul!

Thank you for PR. I will merge it in separate branch.

I do not recommend to use this plugin with Grails 3. My opinion, using WebJars (http://www.webjars.org/) are more flexible way to do the same things.

`build.gradle` example:

``` groovy
repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://repo.grails.org/grails/core' }
    maven { url "http://dl.bintray.com/webjars/maven" }
}

dependencies {
    // ...

    // webjars
    provided 'org.webjars.bower:font-awesome:4.4.0'
}
```

Then you can put `font-awesome.css` into `assets/stylesheets` folder:

``` css
/*
*= require webjars/font-awesome/4.4.0/css/font-awesome.css
*/
```

After that you can attach this stylesheet to use GSP by this way:

``` html
<asset:stylesheet src="font-awesome"/>
```

**Comment by PaulWaldo** [comment]
That looks cool, Alexey.  My goal was to provide a quick upgrade path to grails 2.x projects that use this plugin.

**Comment by PaulWaldo** [comment]
Thank you, Alexey!  I realized the build is failing and so have another PR.  Do you have a Binary account to publish to?

**Comment by donbeave** [comment]
Thank you for PR. Merged.

I will publish it on Bintray, but first I will do some changes. Version will be changed to. I want to use same version with original font-awesome library.

**Comment by PaulWaldo** [comment]
Thanks, Alexey.  Please let me know when it is updated and I'll let everyone know on the grails google group.

**Pull request merged**
